version: '2'
services:
  balanceador:
    image: nginx:1.13
    volumes: 
        - './nginx.conf:/etc/nginx/conf.d/nginx.conf'    
    ports:
      - "3000:3000"
    depends_on:
      - node1
      - node2
  node1:
    image: nicopaez/password-api:2.1.0
    ports:
      - 10001:3000    
  node2:
    image: nicopaez/password-api:2.1.0
    ports:
      - 10002:3000    
